#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-2.0
# tools/cberry_htop.sh — replace the C-Berry console session with htop
# (or any other full-screen TUI). Uses a systemd drop-in so the change
# is reversible without touching the main unit.
#
# Usage:
#   sudo ./cberry_htop.sh on    [CMD ...]   # default CMD is 'htop'
#   sudo ./cberry_htop.sh off               # back to the login shell
#   sudo ./cberry_htop.sh status
#
# Examples:
#   sudo ./cberry_htop.sh on
#   sudo ./cberry_htop.sh on btop
#   sudo ./cberry_htop.sh on watch -n1 'date; uptime'

set -euo pipefail

SVC=cberry-console.service
DROPIN_DIR=/etc/systemd/system/${SVC}.d
DROPIN=${DROPIN_DIR}/htop.conf
DEFAULT_FONT_SIZE=8

need_root() {
    if [[ $EUID -ne 0 ]]; then
        echo "must run as root" >&2
        exit 1
    fi
}

ensure_pkg() {
    local cmd=$1
    if ! command -v "$cmd" >/dev/null 2>&1; then
        echo "==> installing $cmd"
        apt-get update -qq
        apt-get install -y -qq "$cmd"
    fi
}

do_on() {
    need_root
    if ! systemctl cat "$SVC" >/dev/null 2>&1; then
        echo "$SVC not installed. Run cberry_console.sh install first." >&2
        exit 1
    fi

    shift || true
    local args=("$@")
    [[ ${#args[@]} -eq 0 ]] && args=(htop)

    ensure_pkg "${args[0]}"

    # Quote each argument for the unit file.
    local quoted=""
    for a in "${args[@]}"; do
        quoted+=" $(printf '%q' "$a")"
    done

    install -d "$DROPIN_DIR"
    cat > "$DROPIN" <<EOF
# Generated by cberry_htop.sh. Remove with: cberry_htop.sh off
[Service]
ExecStart=
ExecStart=/usr/bin/fbterm --font-size=${DEFAULT_FONT_SIZE} --${quoted}
EOF
    systemctl daemon-reload
    systemctl restart "$SVC"
    echo "==> $SVC now runs:${quoted}"
}

do_off() {
    need_root
    rm -f "$DROPIN"
    rmdir --ignore-fail-on-non-empty "$DROPIN_DIR" 2>/dev/null || true
    systemctl daemon-reload
    systemctl restart "$SVC"
    echo "==> reverted to default login shell"
}

case "${1:-status}" in
    on)     do_on "$@" ;;
    off)    do_off ;;
    status)
        if [[ -f $DROPIN ]]; then
            echo "drop-in active:"
            cat "$DROPIN"
        else
            echo "drop-in not present (default shell mode)"
        fi
        systemctl status "$SVC" --no-pager 2>&1 || true
        ;;
    *) echo "usage: $0 {on [CMD ...]|off|status}" >&2; exit 1 ;;
esac
