#!/usr/bin/env bash
# tools/cberry_xmonitor.sh — turn the C-Berry LCD into the system's
# primary monitor by running Xorg directly on /dev/fb1.
#
# Drops a custom Xorg config that:
#   - uses xserver-xorg-video-fbdev,
#   - binds Device "C-Berry" to /dev/fb1,
#   - sets a 320x240 virtual screen (the panel's native resolution),
#   - disables HDMI/KMS so Xorg won't grab fb0.
#
# After install, the desktop manager (lightdm / autologin) will show
# its session on the C-Berry instead of HDMI on the next boot.
#
# Usage:
#   sudo ./cberry_xmonitor.sh install    # write config + restart display
#   sudo ./cberry_xmonitor.sh remove     # restore HDMI as primary
#   sudo ./cberry_xmonitor.sh status
#
# Notes:
#   - 320x240 is tiny: most desktops will be unreadable. Best paired
#     with a kiosk app (e.g. Chromium --kiosk pointing at a dashboard
#     URL, or matchbox-window-manager with a single fullscreen window).
#   - Ensure the cberryfb module is loaded (it normally is via DT
#     overlay) before starting X.

set -euo pipefail

CONF=/etc/X11/xorg.conf.d/99-cberry.conf
PKG="xserver-xorg-video-fbdev xinit x11-xserver-utils"

need_root() {
    if [[ $EUID -ne 0 ]]; then
        echo "must run as root" >&2
        exit 1
    fi
}

do_install() {
    need_root

    echo "==> installing Xorg fbdev driver"
    apt-get update -qq
    # shellcheck disable=SC2086
    apt-get install -y -qq $PKG

    echo "==> writing $CONF"
    install -d /etc/X11/xorg.conf.d
    cat > "$CONF" <<'EOF'
# Force Xorg to drive the C-Berry LCD (/dev/fb1) as the primary screen.
# Generated by cberry_xmonitor.sh — do not edit by hand.

Section "Device"
    Identifier  "C-Berry"
    Driver      "fbdev"
    Option      "fbdev" "/dev/fb1"
EndSection

Section "Monitor"
    Identifier  "C-Berry-Mon"
    HorizSync   30-70
    VertRefresh 50-75
EndSection

Section "Screen"
    Identifier  "C-Berry-Screen"
    Device      "C-Berry"
    Monitor     "C-Berry-Mon"
    DefaultDepth 16
    SubSection "Display"
        Depth     16
        Modes     "320x240"
        Virtual   320 240
    EndSubSection
EndSection

Section "ServerLayout"
    Identifier  "C-Berry-Layout"
    Screen 0    "C-Berry-Screen"
EndSection
EOF

    echo "==> done. Reboot or 'sudo systemctl restart lightdm' to see it."
}

do_remove() {
    need_root
    rm -f "$CONF"
    echo "==> $CONF removed. Reboot to restore HDMI as primary."
}

case "${1:-status}" in
    install) do_install ;;
    remove)  do_remove ;;
    status)
        if [[ -f $CONF ]]; then
            echo "config installed at $CONF:"
            cat "$CONF"
        else
            echo "not installed"
        fi
        ;;
    *) echo "usage: $0 {install|remove|status}" >&2; exit 1 ;;
esac
